import { Migration } from '@mikro-orm/migrations';

export class Migration20260526150000_lightweight_planner extends Migration {
  async up(): Promise<void> {
    // 1. Add allowed_planting_statuses column to action_templates
    await this.execute(`
      ALTER TABLE action_templates
        ADD COLUMN IF NOT EXISTS allowed_planting_statuses text[] NULL
    `);

    // 2. Populate status restrictions per template slug
    //    Siew nasion – only valid when seedling is being prepared
    await this.execute(`
      UPDATE action_templates
        SET allowed_planting_statuses = ARRAY['SEEDLING_PREPARED']
      WHERE slug = 'siew-nasion'
    `);

    //    Pikowanie siewek – only valid in SEEDLING_PREPARED stage
    await this.execute(`
      UPDATE action_templates
        SET allowed_planting_statuses = ARRAY['SEEDLING_PREPARED']
      WHERE slug = 'pikowanie-siewek'
    `);

    //    Sadzenie rozsady – only valid when seedling is ready for transplant
    await this.execute(`
      UPDATE action_templates
        SET allowed_planting_statuses = ARRAY['SEEDLING_READY_FOR_TRANSPLANT']
      WHERE slug = 'sadzenie-rozsady'
    `);

    //    Podwiązywanie roślin – valid once plant is in ground, up to harvest
    await this.execute(`
      UPDATE action_templates
        SET allowed_planting_statuses = ARRAY['IN_GROUND', 'READY_FOR_FINAL_HARVEST']
      WHERE slug = 'podwiazywanie-roslin'
    `);

    //    Zbiór plonów (AUTO/planting) – only when ready for final harvest
    await this.execute(`
      UPDATE action_templates
        SET allowed_planting_statuses = ARRAY['READY_FOR_FINAL_HARVEST']
      WHERE slug = 'zbior-plonow'
        AND generation_mode = 'AUTO'
        AND target = 'planting'
    `);

    //    Kontrola gotowości do zbioru – valid in active growing and harvest-ready stages
    await this.execute(`
      UPDATE action_templates
        SET allowed_planting_statuses = ARRAY['IN_GROUND', 'READY_FOR_FINAL_HARVEST']
      WHERE slug = 'kontrola-gotowosci-do-zbioru'
    `);

    // 3. Cancel stale PENDING ActionTasks created by automation
    //    (source_type = 'AUTOMATION'); manual tasks (source_type != 'AUTOMATION') are left intact.

    //    3a. Cancel tasks generated from WEATHER_TRIGGERED templates
    await this.execute(`
      UPDATE action_tasks at
        SET status = 'CANCELLED',
            cancelled_at = NOW(),
            cancellation_reason = 'lightweight_planner_migration:weather_triggered_disabled'
      FROM action_templates tmpl
      WHERE at.action_template_id = tmpl.id
        AND at.status = 'PENDING'
        AND at.source_type = 'AUTOMATION'
        AND tmpl.generation_mode = 'WEATHER_TRIGGERED'
    `);

    //    3b. Cancel tasks generated by weather planner (source = 'WEATHER')
    await this.execute(`
      UPDATE action_tasks
        SET status = 'CANCELLED',
            cancelled_at = NOW(),
            cancellation_reason = 'lightweight_planner_migration:weather_tasks_disabled'
      WHERE status = 'PENDING'
        AND source_type = 'AUTOMATION'
        AND source = 'WEATHER'
    `);

    //    3c. Cancel "Zbiór plonów" tasks for plantings that are NOT READY_FOR_FINAL_HARVEST
    await this.execute(`
      UPDATE action_tasks at
        SET status = 'CANCELLED',
            cancelled_at = NOW(),
            cancellation_reason = 'lightweight_planner_migration:zbior_wrong_status'
      FROM action_templates tmpl
      JOIN plantings p ON p.id = at.planting_id
      WHERE at.action_template_id = tmpl.id
        AND at.status = 'PENDING'
        AND at.source_type = 'AUTOMATION'
        AND tmpl.slug = 'zbior-plonow'
        AND tmpl.generation_mode = 'AUTO'
        AND p.status != 'READY_FOR_FINAL_HARVEST'
    `);

    //    3d. Cancel ROUTINE planting tasks for plantings NOT in active growing stages
    await this.execute(`
      UPDATE action_tasks at
        SET status = 'CANCELLED',
            cancelled_at = NOW(),
            cancellation_reason = 'lightweight_planner_migration:routine_wrong_status'
      FROM action_templates tmpl
      JOIN plantings p ON p.id = at.planting_id
      WHERE at.action_template_id = tmpl.id
        AND at.status = 'PENDING'
        AND at.source_type = 'AUTOMATION'
        AND tmpl.generation_mode = 'ROUTINE'
        AND tmpl.target = 'planting'
        AND p.status NOT IN ('IN_GROUND', 'READY_FOR_FINAL_HARVEST')
    `);

    //    3e. Cancel all AUTOMATION tasks for plantings in terminal / pre-active statuses
    await this.execute(`
      UPDATE action_tasks at
        SET status = 'CANCELLED',
            cancelled_at = NOW(),
            cancellation_reason = 'lightweight_planner_migration:planting_terminal_status'
      FROM plantings p
      WHERE at.planting_id = p.id
        AND at.status = 'PENDING'
        AND at.source_type = 'AUTOMATION'
        AND p.status IN ('NEW', 'HARVESTED', 'CLEARED', 'FAILED', 'CANCELLED')
    `);
  }

  async down(): Promise<void> {
    // Remove the column (status restrictions)
    await this.execute(`
      ALTER TABLE action_templates
        DROP COLUMN IF EXISTS allowed_planting_statuses
    `);
    // Cancelled tasks cannot be automatically restored; down() only reverts the schema change.
  }
}
