export enum AnalyticsEventType {
  ARTICLE_VIEW = 'ARTICLE_VIEW',
  ARTICLE_ENGAGED = 'ARTICLE_ENGAGED',
  ARTICLE_SCROLL_50 = 'ARTICLE_SCROLL_50',
  ARTICLE_SCROLL_90 = 'ARTICLE_SCROLL_90',
  VEGETABLE_ADDED_TO_BED = 'VEGETABLE_ADDED_TO_BED',
}
