export enum CultivationEnvironment {
  GROUND_OUTDOOR = 'GROUND_OUTDOOR',
  RAISED_BED_OUTDOOR = 'RAISED_BED_OUTDOOR',
  POT_OUTDOOR = 'POT_OUTDOOR',
  POT_INDOOR = 'POT_INDOOR',
  GREENHOUSE = 'GREENHOUSE',
  TUNNEL = 'TUNNEL',
}
