export enum NotificationIntensity {
  IMPORTANT_ONLY = 'IMPORTANT_ONLY',
  BALANCED = 'BALANCED',
  ALL = 'ALL',
}

export enum NotificationDeliveryPolicy {
  PUSH_IMMEDIATE = 'PUSH_IMMEDIATE',
  PUSH_DIGEST = 'PUSH_DIGEST',
  CENTER_ONLY = 'CENTER_ONLY',
  PLAN_ONLY = 'PLAN_ONLY',
}

export enum NotificationType {
  TASKS_GENERATED = 'TASKS_GENERATED',
  DAILY_TASKS_SUMMARY = 'DAILY_TASKS_SUMMARY',
  WEATHER_STATUS_CHANGED = 'WEATHER_STATUS_CHANGED',
  GARDEN_RISK_CHANGED = 'GARDEN_RISK_CHANGED',
  WEATHER_ALERTS_SUMMARY = 'WEATHER_ALERTS_SUMMARY',
  ARTICLE_RECOMMENDED = 'ARTICLE_RECOMMENDED',
  LIFECYCLE_SUGGESTION = 'LIFECYCLE_SUGGESTION',
  WEEKLY_DIGEST = 'WEEKLY_DIGEST',
}

export enum NotificationRouteTarget {
  HOME = 'HOME',
  BEDS_LIST = 'BEDS_LIST',
  BED_DETAIL = 'BED_DETAIL',
  PLANTING_DETAIL = 'PLANTING_DETAIL',
  PLANNER = 'PLANNER',
  PLANNER_TASKS = 'PLANNER_TASKS',
  WEATHER = 'WEATHER',
  GARDEN_RISK = 'GARDEN_RISK',
  WEATHER_ALERTS = 'WEATHER_ALERTS',
  WEATHER_ALERT_DETAIL = 'WEATHER_ALERT_DETAIL',
  ARTICLE_DETAIL = 'ARTICLE_DETAIL',
  ARTICLES_LIST = 'ARTICLES_LIST',
  NOTIFICATION_CENTER = 'NOTIFICATION_CENTER',
}

export enum NotificationPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum NotificationEventStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
}

export enum NotificationBatchStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
}

export enum NotificationDeliveryStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}
