export enum PlantingEventType {
  PLANTING_CREATED = 'PLANTING_CREATED',
  PLANTING_SOWED = 'PLANTING_SOWED',
  PLANTING_TRANSPLANTED = 'PLANTING_TRANSPLANTED',
  PLANTING_STARTED = 'PLANTING_STARTED',
  PLANTING_STATUS_CHANGED = 'PLANTING_STATUS_CHANGED',
  PLANTING_CANCELLED = 'PLANTING_CANCELLED',
  PLANTING_HARVEST_STARTED = 'PLANTING_HARVEST_STARTED',
  PLANTING_HARVEST_FINISHED = 'PLANTING_HARVEST_FINISHED',
  PLANTING_ACTION_COMPLETED = 'PLANTING_ACTION_COMPLETED',
}
