export enum PlantingStatus {
  NEW = 'NEW',
  IN_GROUND = 'IN_GROUND',
  READY_FOR_FINAL_HARVEST = 'READY_FOR_FINAL_HARVEST',
  HARVESTED = 'HARVESTED',
  CLEARED = 'CLEARED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum PlantingStartMethod {
  DIRECT_SOW = 'DIRECT_SOW',
  TRANSPLANT = 'TRANSPLANT',
  PURCHASED_SEEDLING = 'PURCHASED_SEEDLING',
}
