export enum WarningCode {
  SOIL_NOT_RECOMMENDED = 'SOIL_NOT_RECOMMENDED',
  PH_OUT_OF_RANGE = 'PH_OUT_OF_RANGE',
  DEPTH_TOO_SMALL = 'DEPTH_TOO_SMALL',
  NPK_TOO_LOW = 'NPK_TOO_LOW',
  ROTATION_RISK = 'ROTATION_RISK',
  WATER_RETENTION_MISMATCH = 'WATER_RETENTION_MISMATCH',
  DRAINAGE_MISMATCH = 'DRAINAGE_MISMATCH',
  FAMILY_REPETITION = 'FAMILY_REPETITION',
  HARVEST_WINDOW_MISSED = 'HARVEST_WINDOW_MISSED',
  SUBOPTIMAL_SOWING_TIME = 'SUBOPTIMAL_SOWING_TIME',
  EXPERIMENTAL_SETUP = 'EXPERIMENTAL_SETUP',
}

export enum WarningSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}
