export enum WarningCode {
  SOIL_NOT_RECOMMENDED = 'SOIL_NOT_RECOMMENDED',
  PH_OUT_OF_RANGE = 'PH_OUT_OF_RANGE',
  DEPTH_TOO_SMALL = 'DEPTH_TOO_SMALL',
  NPK_TOO_LOW = 'NPK_TOO_LOW',
  ROTATION_RISK = 'ROTATION_RISK',
  WATER_RETENTION_MISMATCH = 'WATER_RETENTION_MISMATCH',
  DRAINAGE_MISMATCH = 'DRAINAGE_MISMATCH',
}

export enum WarningSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}
